### ISSUE TITLE
Error suppression causes important debug information to be lost

### ISSUE THREAD

**Issue by shachibista** [swiftmailer/swiftmailer#1201]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | no
| RFC?                | no
| How used?           | Standalone/Symfony/3party
| Swiftmailer version | 6.2.1
| PHP version         | 7.1.30

### Observed behaviour
Error suppression causes warnings from `stream_socket_client` to be hidden and `errno` is 0.

### Expected behaviour
Warnings from `stream_socket_client` should not be hidden by default.

### Example
When trying to connect to a mail server with `ssl` at port `465`, with error suppression:

```
Fatal error: Uncaught Swift_TransportException: Connection could not be established with host mail.example.org [ #0] in /mailtest/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:269
Stack trace:
#0 /mailtest/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php(58): Swift_Transport_StreamBuffer->establishSocketConnection()
#1 /mailtest/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(143): Swift_Transport_StreamBuffer->initialize(Array)
#2 /mailtest/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(65): Swift_Transport_AbstractSmtpTransport->start()
#3 /mailtest/test.php(19): Swift_Mailer->send(Object(Swift_Message))
#4 {main}
  thrown in /mailtest/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php on line 269
```
Without error suppression:

```
Warning: stream_socket_client(): Peer certificate CN=`mail.somewhere-else.net' did not match expected CN=`mail.exmaple.org' in /mailtest/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php on line 267

Warning: stream_socket_client(): Failed to enable crypto in /mailtest/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php on line 267

Warning: stream_socket_client(): unable to connect to ssl://mail.example.org:465 (Unknown error) in /mailtest/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php on line 267

Fatal error: Uncaught Swift_TransportException: Connection could not be established with host mail.example.org [ #0] in /mailtest/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:269
Stack trace:
#0 /mailtest/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php(58): Swift_Transport_StreamBuffer->establishSocketConnection()
#1 /mailtest/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(143): Swift_Transport_StreamBuffer->initialize(Array)
#2 /mailtest/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(65): Swift_Transport_AbstractSmtpTransport->start()
#3 /mailtest/test.php(19): Swift_Mailer->send(Object(Swift_Message))
#4 {main}
  thrown in /mailtest/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php on line 269
```

Error is suppressed at line 267 in `StreamBuffer.php`:

```php
$this->stream = @stream_socket_client($host.':'.$this->params['port'], $errno, $errstr, $timeout, STREAM_CLIENT_CONNECT, $streamContext);
```

**Comment by fabpot** [comment]
Should be fixed by #1202.
