### ISSUE TITLE
fwrite(): SSL: Connection reset by peer in StreamBuffer.php:232

### ISSUE THREAD

**Issue by toshcn** [swiftmailer/swiftmailer#855]
I use Yii2 , the error is when I send the second e-mail it show.Who can help me？
send the first e-mail is success.
send the second e-mail is error. why?

~~~html
yii\base\ErrorException: fwrite(): SSL: Connection reset by peer in /home/www/mysite/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:232
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'fwrite(): SSL: ...', '/home/www/len16...', 232, Array)
#1 /home/www/mysite/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php(232): fwrite(Resource id #179, 'MAIL FROM:<len1...')
#2 /home/www/mysite/vendor/swiftmailer/swiftmailer/lib/classes/Swift/ByteStream/AbstractFilterableInputStream.php(173): Swift_Transport_StreamBuffer->_commit('MAIL FROM:<len1...')
#3 /home/www/mysite/vendor/swiftmailer/swiftmailer/lib/classes/Swift/ByteStream/AbstractFilterableInputStream.php(92): Swift_ByteStream_AbstractFilterableInputStream->_doWrite('MAIL FROM:<len1...')
#4 /home/www/mysite/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(276): Swift_ByteStream_AbstractFilterableInputStream->write('MAIL FROM:<len1...')
#5 /home/www/mysite/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(270): Swift_Transport_AbstractSmtpTransport->executeCommand('MAIL FROM:<len1...', Array, Array)
#6 /home/www/mysite/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(348): Swift_Transport_EsmtpTransport->executeCommand('MAIL FROM:<len1...', Array)
#7 /home/www/mysite/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(416): Swift_Transport_EsmtpTransport->_doMailFromCommand('len***@len***.c...')
#8 /home/www/mysite/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(443): Swift_Transport_AbstractSmtpTransport->_doMailTransaction(Object(Swift_Message), 'len***@len***.c...', Array, Array)
#9 /home/www/mysite/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(176): Swift_Transport_AbstractSmtpTransport->_sendTo(Object(Swift_Message), 'len***@len***.c...', Array, Array)
#10 /home/www/mysite/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(85): Swift_Transport_AbstractSmtpTransport->send(Object(Swift_Message), Array)
#11 /home/www/mysite/vendor/yiisoft/yii2-swiftmailer/Mailer.php(146): Swift_Mailer->send(Object(Swift_Message))
#12 /home/www/mysite/vendor/yiisoft/yii2/mail/BaseMailer.php(260): yii\swiftmailer\Mailer->sendMessage(Object(yii\swiftmailer\Message))
#13 /home/www/mysite/vendor/yiisoft/yii2/mail/BaseMessage.php(48): yii\mail\BaseMailer->send(Object(yii\swiftmailer\Message))
#14 /home/www/mysite/console/controllers/WorkerController.php(54): yii\mail\BaseMessage->send()
#15 [internal function]: console\controllers\WorkerController->actionTubeInvitEmail(Object(Pheanstalk\Job))
#16 /home/www/mysite/vendor/udokmeci/yii2-beanstalk/src/udokmeci/yii2beanstalk/BeanstalkController.php(362): call_user_func_array(Array, Array)
#17 /home/www/mysite/vendor/udokmeci/yii2-beanstalk/src/udokmeci/yii2beanstalk/BeanstalkController.php(322): udokmeci\yii2beanstalk\BeanstalkController->executeJob('actionTubeInvit...', Object(Pheanstalk\Job))
#18 /home/www/mysite/vendor/yiisoft/yii2/base/Controller.php(152): udokmeci\yii2beanstalk\BeanstalkController->beforeAction(Object(yii\base\InlineAction))
#19 /home/www/mysite/vendor/yiisoft/yii2/console/Controller.php(128): yii\base\Controller->runAction('', Array)
#20 /home/www/mysite/vendor/yiisoft/yii2/base/Module.php(454): yii\console\Controller->runAction('', Array)
#21 /home/www/mysite/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('worker', Array)
#22 /home/www/mysite/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('worker', Array)
#23 /home/www/mysite/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#24 /home/www/mysite/yii(31): yii\base\Application->run()
#25 {main}
~~~

**Comment by sstok** [comment]
`Connection reset by peer` usually indicates a network problem like a flood protection.
It's not something that is easy to fix, I suggest you contact your hosting provider for more information.

And please ask support questions on http://stackoverflow.com/ as you will have much bigger change to answers. The issue tracker is only meant for bugs (reproducible in isolation without a framework in place) and feature requests. Thanks 👍
